// Generated by scripts/import-fandom-character-images.mjs
const asset = (path: string) => `${import.meta.env.BASE_URL}${path}`

export type CharacterImageSource = {
  id: string
  label: string
  localPath: string
  fandomFile: string
  sourceUrl: string
  knownByEpisode: string
}

export const characterImageById: Record<string, string> = {
  "ned-stark": asset("images/characters/ned-stark.jpg"),
  "catelyn-stark": asset("images/characters/catelyn-stark.jpg"),
  "robb-stark": asset("images/characters/robb-stark.png"),
  "sansa-stark": asset("images/characters/sansa-stark.png"),
  "arya-stark": asset("images/characters/arya-stark.png"),
  "bran-stark": asset("images/characters/bran-stark.png"),
  "rickon-stark": asset("images/characters/rickon-stark.jpg"),
  "jon-snow": asset("images/characters/jon-snow.jpg"),
  "benjen-stark": asset("images/characters/benjen-stark.jpg"),
  "lyanna-stark": asset("images/characters/lyanna-stark.jpg"),
  "robert-baratheon": asset("images/characters/robert-baratheon.jpg"),
  "cersei-lannister": asset("images/characters/cersei-lannister.jpg"),
  "jaime-lannister": asset("images/characters/jaime-lannister.jpg"),
  "tyrion-lannister": asset("images/characters/tyrion-lannister.png"),
  "joffrey-baratheon": asset("images/characters/joffrey-baratheon.jpg"),
  "myrcella-baratheon": asset("images/characters/myrcella-baratheon.jpg"),
  "tommen-baratheon": asset("images/characters/tommen-baratheon.jpg"),
  "jon-arryn": asset("images/characters/jon-arryn.jpg"),
  "lysa-arryn": asset("images/characters/lysa-arryn.jpg"),
  "theon-greyjoy": asset("images/characters/theon-greyjoy.png"),
  "daenerys-targaryen": asset("images/characters/daenerys-targaryen.jpg"),
  "viserys-targaryen": asset("images/characters/viserys-targaryen.png"),
  "khal-drogo": asset("images/characters/khal-drogo.jpg"),
  "jorah-mormont": asset("images/characters/jorah-mormont.png"),
  "illyrio-mopatis": asset("images/characters/illyrio-mopatis.png"),
}

export const characterImageSources: CharacterImageSource[] = [
  {
    "id": "ned-stark",
    "label": "Eddard Stark",
    "localPath": asset("images/characters/ned-stark.jpg"),
    "fandomFile": "Eddard 1x01.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Eddard_1x01.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "catelyn-stark",
    "label": "Catelyn Stark",
    "localPath": asset("images/characters/catelyn-stark.jpg"),
    "fandomFile": "Catelyn 1x01.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Catelyn_1x01.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "robb-stark",
    "label": "Robb Stark",
    "localPath": asset("images/characters/robb-stark.png"),
    "fandomFile": "Lord Robb in Winterfell.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Lord_Robb_in_Winterfell.png",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "sansa-stark",
    "label": "Sansa Stark",
    "localPath": asset("images/characters/sansa-stark.png"),
    "fandomFile": "SansaStarkS1Promo.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:SansaStarkS1Promo.png",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "arya-stark",
    "label": "Arya Stark",
    "localPath": asset("images/characters/arya-stark.png"),
    "fandomFile": "Winter is Coming arya closer look.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_arya_closer_look.png",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "bran-stark",
    "label": "Bran Stark",
    "localPath": asset("images/characters/bran-stark.png"),
    "fandomFile": "Bran and Summer s1 in winterfell.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Bran_and_Summer_s1_in_winterfell.png",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "rickon-stark",
    "label": "Rickon Stark",
    "localPath": asset("images/characters/rickon-stark.jpg"),
    "fandomFile": "Rickon Stark s1 having fun.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Rickon_Stark_s1_having_fun.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "jon-snow",
    "label": "Jon Snow",
    "localPath": asset("images/characters/jon-snow.jpg"),
    "fandomFile": "Winter is Coming Tyrion and Jon.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_Tyrion_and_Jon.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "benjen-stark",
    "label": "Benjen Stark",
    "localPath": asset("images/characters/benjen-stark.jpg"),
    "fandomFile": "Winter is Coming Ned and Benjen.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_Ned_and_Benjen.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "lyanna-stark",
    "label": "Lyanna Stark",
    "localPath": asset("images/characters/lyanna-stark.jpg"),
    "fandomFile": "Winter is Coming Robert crypt.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_Robert_crypt.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "robert-baratheon",
    "label": "Robert Baratheon",
    "localPath": asset("images/characters/robert-baratheon.jpg"),
    "fandomFile": "Robert at Winterfell.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Robert_at_Winterfell.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "cersei-lannister",
    "label": "Cersei Lannister",
    "localPath": asset("images/characters/cersei-lannister.jpg"),
    "fandomFile": "Cersei 1x01.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Cersei_1x01.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "jaime-lannister",
    "label": "Jaime Lannister",
    "localPath": asset("images/characters/jaime-lannister.jpg"),
    "fandomFile": "Jaime-lannister-1x01-winter-is-coming-jaime-lannister-23125077-1280-720.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Jaime-lannister-1x01-winter-is-coming-jaime-lannister-23125077-1280-720.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "tyrion-lannister",
    "label": "Tyrion Lannister",
    "localPath": asset("images/characters/tyrion-lannister.png"),
    "fandomFile": "Winter is Coming Tyrion and Ros.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_Tyrion_and_Ros.png",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "joffrey-baratheon",
    "label": "Joffrey Baratheon",
    "localPath": asset("images/characters/joffrey-baratheon.jpg"),
    "fandomFile": "Winter is Coming joffrey looks at sansa.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_joffrey_looks_at_sansa.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "myrcella-baratheon",
    "label": "Myrcella Baratheon",
    "localPath": asset("images/characters/myrcella-baratheon.jpg"),
    "fandomFile": "Winter is Coming Myrcella Tommen intro.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_Myrcella_Tommen_intro.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "tommen-baratheon",
    "label": "Tommen Baratheon",
    "localPath": asset("images/characters/tommen-baratheon.jpg"),
    "fandomFile": "Winter is Coming Myrcella Tommen intro.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Winter_is_Coming_Myrcella_Tommen_intro.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "jon-arryn",
    "label": "Jon Arryn",
    "localPath": asset("images/characters/jon-arryn.jpg"),
    "fandomFile": "Jon Arryn funeral bier.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Jon_Arryn_funeral_bier.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "lysa-arryn",
    "label": "Lysa Arryn",
    "localPath": asset("images/characters/lysa-arryn.jpg"),
    "fandomFile": "Lysa Arryn infobox.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Lysa_Arryn_infobox.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "theon-greyjoy",
    "label": "Theon Greyjoy",
    "localPath": asset("images/characters/theon-greyjoy.png"),
    "fandomFile": "Jon, Robb and Theon 1x01.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Jon,_Robb_and_Theon_1x01.png",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "daenerys-targaryen",
    "label": "Daenerys Targaryen",
    "localPath": asset("images/characters/daenerys-targaryen.jpg"),
    "fandomFile": "Daenerys and Viserys.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Daenerys_and_Viserys.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "viserys-targaryen",
    "label": "Viserys Targaryen",
    "localPath": asset("images/characters/viserys-targaryen.png"),
    "fandomFile": "Viserys & Illyrio 1x01.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Viserys_%26_Illyrio_1x01.png",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "khal-drogo",
    "label": "Khal Drogo",
    "localPath": asset("images/characters/khal-drogo.jpg"),
    "fandomFile": "Drogo 1x01.jpg",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Drogo_1x01.jpg",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "jorah-mormont",
    "label": "Jorah Mormont",
    "localPath": asset("images/characters/jorah-mormont.png"),
    "fandomFile": "JorahGiftToDaenerysSeason1.PNG",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:JorahGiftToDaenerysSeason1.PNG",
    "knownByEpisode": "s01e01"
  },
  {
    "id": "illyrio-mopatis",
    "label": "Illyrio Mopatis",
    "localPath": asset("images/characters/illyrio-mopatis.png"),
    "fandomFile": "Viserys & Illyrio 1x01.png",
    "sourceUrl": "https://gameofthrones.fandom.com/wiki/File:Viserys_%26_Illyrio_1x01.png",
    "knownByEpisode": "s01e01"
  }
]
