// Generated by scripts/import-commons-images.mjs
const asset = (path: string) => `${import.meta.env.BASE_URL}${path}`

export type ImageAttribution = {
  id: string
  kind: 'portrait' | 'map' | 'place'
  label: string
  localPath: string
  commonsFile: string
  sourceUrl: string
  license: string
  licenseUrl?: string
  artist: string
  characterId?: string
}

export const portraitByCharacterId: Record<string, string> = {
  "ned-stark": asset("images/portraits/ned-stark.jpg"),
  "catelyn-stark": asset("images/portraits/catelyn-stark.jpg"),
  "robb-stark": asset("images/portraits/robb-stark.jpg"),
  "sansa-stark": asset("images/portraits/sansa-stark.jpg"),
  "arya-stark": asset("images/portraits/arya-stark.jpg"),
  "bran-stark": asset("images/portraits/bran-stark.jpg"),
  "jon-snow": asset("images/portraits/jon-snow.jpg"),
  "benjen-stark": asset("images/portraits/benjen-stark.jpg"),
  "robert-baratheon": asset("images/portraits/robert-baratheon.jpg"),
  "cersei-lannister": asset("images/portraits/cersei-lannister.jpg"),
  "jaime-lannister": asset("images/portraits/jaime-lannister.jpg"),
  "tyrion-lannister": asset("images/portraits/tyrion-lannister.jpg"),
  "joffrey-baratheon": asset("images/portraits/joffrey-baratheon.jpg"),
  "myrcella-baratheon": asset("images/portraits/myrcella-baratheon.jpg"),
  "jon-arryn": asset("images/portraits/jon-arryn.jpg"),
  "theon-greyjoy": asset("images/portraits/theon-greyjoy.jpg"),
  "daenerys-targaryen": asset("images/portraits/daenerys-targaryen.png"),
  "viserys-targaryen": asset("images/portraits/viserys-targaryen.jpg"),
  "khal-drogo": asset("images/portraits/khal-drogo.jpg"),
  "jorah-mormont": asset("images/portraits/jorah-mormont.jpg"),
  "illyrio-mopatis": asset("images/portraits/illyrio-mopatis.jpg"),
}

export const locationImageById: Record<string, string> = {
  "winterfell": asset("images/places/winterfell-castle-ward.jpg"),
  "beyond-wall": asset("images/places/beyond-wall-tollymore.jpg"),
  "the-wall": asset("images/places/the-wall-iceland.jpg"),
  "kings-landing": asset("images/places/kings-landing-mdina.jpg"),
  "pento": asset("images/places/pentos-verdala.jpg"),
  "dothraki-camp": asset("images/places/dothraki-camp-azure-window.jpg"),
}

export const knownWorldMap = asset("images/maps/known-world-map.png")

export const imageAttributions: ImageAttribution[] = [
  {
    "id": "ned-stark",
    "kind": "portrait",
    "label": "Sean Bean",
    "localPath": asset("images/portraits/ned-stark.jpg"),
    "commonsFile": "AV0A6306 Sean Bean (cropped).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:AV0A6306_Sean_Bean_(cropped).jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "9EkieraM1",
    "characterId": "ned-stark"
  },
  {
    "id": "catelyn-stark",
    "kind": "portrait",
    "label": "Michelle Fairley",
    "localPath": asset("images/portraits/catelyn-stark.jpg"),
    "commonsFile": "Michelle Fairley by Gage Skidmore 2 (cropped).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Michelle_Fairley_by_Gage_Skidmore_2_(cropped).jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Gage Skidmore",
    "characterId": "catelyn-stark"
  },
  {
    "id": "robb-stark",
    "kind": "portrait",
    "label": "Richard Madden",
    "localPath": asset("images/portraits/robb-stark.jpg"),
    "commonsFile": "Richard Madden by Gage Skidmore 2.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Richard_Madden_by_Gage_Skidmore_2.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Gage Skidmore",
    "characterId": "robb-stark"
  },
  {
    "id": "sansa-stark",
    "kind": "portrait",
    "label": "Sophie Turner",
    "localPath": asset("images/portraits/sansa-stark.jpg"),
    "commonsFile": "Sophie Turner (40553144273) (cropped).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sophie_Turner_(40553144273)_(cropped).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "artist": "Gage Skidmore from Peoria, AZ, United States of America",
    "characterId": "sansa-stark"
  },
  {
    "id": "arya-stark",
    "kind": "portrait",
    "label": "Maisie Williams",
    "localPath": asset("images/portraits/arya-stark.jpg"),
    "commonsFile": "Disrupt SF TechCrunch Disrupt San Francisco 2019 - Day 2 (48838897492) (cropped).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Disrupt_SF_TechCrunch_Disrupt_San_Francisco_2019_-_Day_2_(48838897492)_(cropped).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "artist": "TechCrunch",
    "characterId": "arya-stark"
  },
  {
    "id": "bran-stark",
    "kind": "portrait",
    "label": "Isaac Hempstead Wright",
    "localPath": asset("images/portraits/bran-stark.jpg"),
    "commonsFile": "Isaac Hempstead Wright by Gage Skidmore 3.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Isaac_Hempstead_Wright_by_Gage_Skidmore_3.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Gage Skidmore",
    "characterId": "bran-stark"
  },
  {
    "id": "jon-snow",
    "kind": "portrait",
    "label": "Kit Harington",
    "localPath": asset("images/portraits/jon-snow.jpg"),
    "commonsFile": "Kit harrington by sachyn mital (cropped 2).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kit_harrington_by_sachyn_mital_(cropped_2).jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Sachyn",
    "characterId": "jon-snow"
  },
  {
    "id": "benjen-stark",
    "kind": "portrait",
    "label": "Joseph Mawle",
    "localPath": asset("images/portraits/benjen-stark.jpg"),
    "commonsFile": "Joseph Mawle in Shell 2012.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Joseph_Mawle_in_Shell_2012.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "artist": "Dublin International Film Festival",
    "characterId": "benjen-stark"
  },
  {
    "id": "robert-baratheon",
    "kind": "portrait",
    "label": "Mark Addy",
    "localPath": asset("images/portraits/robert-baratheon.jpg"),
    "commonsFile": "Mark Addy.JPG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mark_Addy.JPG",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "artist": "Caporaletti1983",
    "characterId": "robert-baratheon"
  },
  {
    "id": "cersei-lannister",
    "kind": "portrait",
    "label": "Lena Headey",
    "localPath": asset("images/portraits/cersei-lannister.jpg"),
    "commonsFile": "Headey, Lena (2007) (headshot).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Headey,_Lena_(2007)_(headshot).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "artist": "pinguino k from North Hollywood, USA",
    "characterId": "cersei-lannister"
  },
  {
    "id": "jaime-lannister",
    "kind": "portrait",
    "label": "Nikolaj Coster-Waldau",
    "localPath": asset("images/portraits/jaime-lannister.jpg"),
    "commonsFile": "Nikolaj Coster-Waldau 2022.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nikolaj_Coster-Waldau_2022.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Harald Krichel",
    "characterId": "jaime-lannister"
  },
  {
    "id": "tyrion-lannister",
    "kind": "portrait",
    "label": "Peter Dinklage",
    "localPath": asset("images/portraits/tyrion-lannister.jpg"),
    "commonsFile": "Peter Dinklage by Gage Skidmore 2.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peter_Dinklage_by_Gage_Skidmore_2.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Gage Skidmore",
    "characterId": "tyrion-lannister"
  },
  {
    "id": "joffrey-baratheon",
    "kind": "portrait",
    "label": "Jack Gleeson",
    "localPath": asset("images/portraits/joffrey-baratheon.jpg"),
    "commonsFile": "2023-04-29 18-11-19 ILCE-7C DSC15774 Kiri DxO.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2023-04-29_18-11-19_ILCE-7C_DSC15774_Kiri_DxO.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "artist": "Miguel Discart & Kiri Karma (Photos Vrac)",
    "characterId": "joffrey-baratheon"
  },
  {
    "id": "myrcella-baratheon",
    "kind": "portrait",
    "label": "Aimee Richardson",
    "localPath": asset("images/portraits/myrcella-baratheon.jpg"),
    "commonsFile": "Aimee Richardson by Gage Skidmore.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aimee_Richardson_by_Gage_Skidmore.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Gage Skidmore",
    "characterId": "myrcella-baratheon"
  },
  {
    "id": "jon-arryn",
    "kind": "portrait",
    "label": "John Standing",
    "localPath": asset("images/portraits/jon-arryn.jpg"),
    "commonsFile": "Sir John Standing.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sir_John_Standing.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "artist": "Allan warren",
    "characterId": "jon-arryn"
  },
  {
    "id": "theon-greyjoy",
    "kind": "portrait",
    "label": "Alfie Allen",
    "localPath": asset("images/portraits/theon-greyjoy.jpg"),
    "commonsFile": "Alfie Allen by Gage Skidmore 2.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alfie_Allen_by_Gage_Skidmore_2.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Gage Skidmore",
    "characterId": "theon-greyjoy"
  },
  {
    "id": "daenerys-targaryen",
    "kind": "portrait",
    "label": "Emilia Clarke",
    "localPath": asset("images/portraits/daenerys-targaryen.png"),
    "commonsFile": "Emilia Clarke Dior Roses des Vents.png",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Emilia_Clarke_Dior_Roses_des_Vents.png",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "artist": "https://vimeo.com/condenastrussia",
    "characterId": "daenerys-targaryen"
  },
  {
    "id": "viserys-targaryen",
    "kind": "portrait",
    "label": "Harry Lloyd",
    "localPath": asset("images/portraits/viserys-targaryen.jpg"),
    "commonsFile": "Harry Lloyd 2010.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Harry_Lloyd_2010.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "artist": "https://www.flickr.com/photos/kstatelibrarian/",
    "characterId": "viserys-targaryen"
  },
  {
    "id": "khal-drogo",
    "kind": "portrait",
    "label": "Jason Momoa",
    "localPath": asset("images/portraits/khal-drogo.jpg"),
    "commonsFile": "Jason Momoa (43055621224) (cropped).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jason_Momoa_(43055621224)_(cropped).jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "artist": "Gage Skidmore from Peoria, AZ, United States of America",
    "characterId": "khal-drogo"
  },
  {
    "id": "jorah-mormont",
    "kind": "portrait",
    "label": "Iain Glen",
    "localPath": asset("images/portraits/jorah-mormont.jpg"),
    "commonsFile": "Iain Glen.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Iain_Glen.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "artist": "uberpixelphoto (Alan Chang)",
    "characterId": "jorah-mormont"
  },
  {
    "id": "illyrio-mopatis",
    "kind": "portrait",
    "label": "Roger Allam",
    "localPath": asset("images/portraits/illyrio-mopatis.jpg"),
    "commonsFile": "Roger Allam La Cage 120909 DSCF1622.JPG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Roger_Allam_La_Cage_120909_DSCF1622.JPG",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "artist": "Sonnenuntergang",
    "characterId": "illyrio-mopatis"
  },
  {
    "id": "known-world-map",
    "kind": "map",
    "label": "Westeros map",
    "localPath": asset("images/maps/known-world-map.png"),
    "commonsFile": "Westeros Map.png",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Westeros_Map.png",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "artist": "M1a1n dee $"
  },
  {
    "id": "winterfell",
    "kind": "place",
    "label": "Winterfell filming-location image",
    "localPath": asset("images/places/winterfell-castle-ward.jpg"),
    "commonsFile": "Game Of Thrones Castle Warden Winterfell.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Game_Of_Thrones_Castle_Warden_Winterfell.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "artist": "William Marnoch from Cambridge, UK"
  },
  {
    "id": "beyond-wall",
    "kind": "place",
    "label": "Beyond the Wall forest reference image",
    "localPath": asset("images/places/beyond-wall-tollymore.jpg"),
    "commonsFile": "Tollymore Forest Park - geograph.org.uk - 3206779.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tollymore_Forest_Park_-_geograph.org.uk_-_3206779.jpg",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "artist": "Rossographer"
  },
  {
    "id": "the-wall",
    "kind": "place",
    "label": "The Wall icy landscape reference image",
    "localPath": asset("images/places/the-wall-iceland.jpg"),
    "commonsFile": "Iceland Grimsvoetn 1972-B.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Iceland_Grimsvoetn_1972-B.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "artist": "Roger McLassus"
  },
  {
    "id": "kings-landing",
    "kind": "place",
    "label": "King's Landing filming-location image",
    "localPath": asset("images/places/kings-landing-mdina.jpg"),
    "commonsFile": "Malta Mdina BW 2011-10-05 13-41-26.JPG",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Malta_Mdina_BW_2011-10-05_13-41-26.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Berthold Werner"
  },
  {
    "id": "pento",
    "kind": "place",
    "label": "Pentos filming-location image",
    "localPath": asset("images/places/pentos-verdala.jpg"),
    "commonsFile": "Malta - Siggiewi - Triq il-Buskett - Buskett Gardens + Verdala Palace 03 ies.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Malta_-_Siggiewi_-_Triq_il-Buskett_-_Buskett_Gardens_+_Verdala_Palace_03_ies.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Frank Vincentz"
  },
  {
    "id": "dothraki-camp",
    "kind": "place",
    "label": "Dothraki wedding filming-location image",
    "localPath": asset("images/places/dothraki-camp-azure-window.jpg"),
    "commonsFile": "Malta Gozo, Azure Window (10264176345).jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Malta_Gozo,_Azure_Window_(10264176345).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "artist": "Berit Watkin from Redhill/Surrey, UK"
  }
]
